### ISSUE TITLE
ipv4num doesn't seem to work

### ISSUE THREAD

**Issue by deseven** [delian/node-netflowv9#22]
Hello. I'm trying to use `ipv4num: true` for netflow v5, but i'm getting this error:
```
ReferenceError: decIpv4Rule is not defined
    at new NetFlowV9 (/srv/ilb-netflow/node_modules/node-netflowv9/netflowv9.js:57:30)
    at NetFlowV9 (/srv/ilb-netflow/node_modules/node-netflowv9/netflowv9.js:42:46)
```

**Comment by delian** [comment]
Let me check

Delian
